# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barely_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Barely(object):
    def setupUi(self, Barely):
        Barely.setObjectName("Barely")
        Barely.resize(400, 620)
        Barely.setMinimumSize(QtCore.QSize(400, 620))
        Barely.setMaximumSize(QtCore.QSize(400, 620))
        Barely.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/barely_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Barely.setWindowIcon(icon)
        Barely.setStyleSheet("background-color: #333333;")
        self.centralwidget = QtWidgets.QWidget(Barely)
        self.centralwidget.setObjectName("centralwidget")
        self.files_display = QtWidgets.QListWidget(self.centralwidget)
        self.files_display.setGeometry(QtCore.QRect(20, 20, 361, 261))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.files_display.setFont(font)
        self.files_display.setFocusPolicy(QtCore.Qt.NoFocus)
        self.files_display.setAcceptDrops(True)
        self.files_display.setStyleSheet("color: #DDDDDD;\n"
"selection-background-color: #583030;\n"
"padding: 5px;")
        self.files_display.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.files_display.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.files_display.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.files_display.setObjectName("files_display")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 300, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FF5050;")
        self.label.setObjectName("label")
        self.now_playing_label = QtWidgets.QLabel(self.centralwidget)
        self.now_playing_label.setGeometry(QtCore.QRect(30, 330, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.now_playing_label.setFont(font)
        self.now_playing_label.setStyleSheet("color: #DDDDDD;")
        self.now_playing_label.setObjectName("now_playing_label")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(250, 300, 120, 20))
        self.volume_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volume_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 2px;\n"
"    border-radius: 1px;\n"
"    background: #CCCCCC;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #FF3333;\n"
"    margin: -4px 0;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"}")
        self.volume_slider.setMaximum(100)
        self.volume_slider.setProperty("value", 50)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.control_buttons = QtWidgets.QFrame(self.centralwidget)
        self.control_buttons.setGeometry(QtCore.QRect(30, 480, 351, 81))
        self.control_buttons.setStyleSheet("QPushButton {\n"
"    background-color: #3F3F42;\n"
"    border: 1px solid #606060;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #606060;\n"
"}")
        self.control_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_buttons.setObjectName("control_buttons")
        self.prev_btn = QtWidgets.QPushButton(self.control_buttons)
        self.prev_btn.setGeometry(QtCore.QRect(0, 50, 30, 30))
        self.prev_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prev_btn.setStyleSheet("border-radius: 15px;")
        self.prev_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev_btn.setIcon(icon1)
        self.prev_btn.setObjectName("prev_btn")
        self.skip_back_btn = QtWidgets.QPushButton(self.control_buttons)
        self.skip_back_btn.setGeometry(QtCore.QRect(40, 40, 40, 40))
        self.skip_back_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skip_back_btn.setStyleSheet("border-radius: 20px;")
        self.skip_back_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_back_btn.setIcon(icon2)
        self.skip_back_btn.setObjectName("skip_back_btn")
        self.play_pause_btn = QtWidgets.QPushButton(self.control_buttons)
        self.play_pause_btn.setGeometry(QtCore.QRect(100, 0, 80, 80))
        self.play_pause_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.play_pause_btn.setToolTip("")
        self.play_pause_btn.setToolTipDuration(-1)
        self.play_pause_btn.setWhatsThis("")
        self.play_pause_btn.setStyleSheet("border-radius: 40px;")
        self.play_pause_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play_pause_btn.setIcon(icon3)
        self.play_pause_btn.setIconSize(QtCore.QSize(32, 32))
        self.play_pause_btn.setCheckable(False)
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.stop_btn = QtWidgets.QPushButton(self.control_buttons)
        self.stop_btn.setGeometry(QtCore.QRect(190, 20, 50, 50))
        self.stop_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop_btn.setStyleSheet("border-radius: 25px;")
        self.stop_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon4)
        self.stop_btn.setObjectName("stop_btn")
        self.skip_forwards_btn = QtWidgets.QPushButton(self.control_buttons)
        self.skip_forwards_btn.setGeometry(QtCore.QRect(260, 40, 40, 40))
        self.skip_forwards_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skip_forwards_btn.setStyleSheet("border-radius: 20px;")
        self.skip_forwards_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_forwards_btn.setIcon(icon5)
        self.skip_forwards_btn.setObjectName("skip_forwards_btn")
        self.next_btn = QtWidgets.QPushButton(self.control_buttons)
        self.next_btn.setGeometry(QtCore.QRect(310, 50, 30, 30))
        self.next_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.next_btn.setStyleSheet("border-radius: 15px;")
        self.next_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon6)
        self.next_btn.setObjectName("next_btn")
        self.position_slider_frame = QtWidgets.QFrame(self.centralwidget)
        self.position_slider_frame.setGeometry(QtCore.QRect(30, 390, 341, 41))
        self.position_slider_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.position_slider_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.position_slider_frame.setObjectName("position_slider_frame")
        self.current_position_label = QtWidgets.QLabel(self.position_slider_frame)
        self.current_position_label.setGeometry(QtCore.QRect(0, 20, 60, 20))
        self.current_position_label.setStyleSheet("color: #DDDDDD;\n"
"margin-left: 5px;")
        self.current_position_label.setObjectName("current_position_label")
        self.duration_label = QtWidgets.QLabel(self.position_slider_frame)
        self.duration_label.setGeometry(QtCore.QRect(280, 20, 60, 20))
        self.duration_label.setMouseTracking(False)
        self.duration_label.setStyleSheet("color: #DDDDDD;\n"
"margin-right: 5px;")
        self.duration_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.duration_label.setObjectName("duration_label")
        self.position_slider = QtWidgets.QSlider(self.position_slider_frame)
        self.position_slider.setGeometry(QtCore.QRect(0, 0, 341, 20))
        self.position_slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.position_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: #DDDDDD;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #FF2222;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin: -4px 0;\n"
"    border-radius: 6px;\n"
"}")
        self.position_slider.setOrientation(QtCore.Qt.Horizontal)
        self.position_slider.setObjectName("position_slider")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 302, 16, 16))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/resources/volume.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.position_slider_frame.raise_()
        self.control_buttons.raise_()
        self.files_display.raise_()
        self.label.raise_()
        self.now_playing_label.raise_()
        self.volume_slider.raise_()
        self.label_2.raise_()
        Barely.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Barely)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menuBar.setStyleSheet("background-color: #583030;\n"
"color: #DDDDDD;")
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        Barely.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(Barely)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon7)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(Barely)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/resources/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon8)
        self.actionClose.setObjectName("actionClose")
        self.actionRemove_selected = QtWidgets.QAction(Barely)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/resources/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_selected.setIcon(icon9)
        self.actionRemove_selected.setObjectName("actionRemove_selected")
        self.actionRemove_all = QtWidgets.QAction(Barely)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/resources/explosion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_all.setIcon(icon10)
        self.actionRemove_all.setObjectName("actionRemove_all")
        self.actionNext = QtWidgets.QAction(Barely)
        self.actionNext.setIcon(icon6)
        self.actionNext.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(Barely)
        self.actionPrevious.setIcon(icon1)
        self.actionPrevious.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionPlay_pause = QtWidgets.QAction(Barely)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/resources/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/resources/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPlay_pause.setIcon(icon11)
        self.actionPlay_pause.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionPlay_pause.setObjectName("actionPlay_pause")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRemove_selected)
        self.menuFile.addAction(self.actionRemove_all)
        self.menuFile.addAction(self.actionClose)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Barely)
        QtCore.QMetaObject.connectSlotsByName(Barely)

    def retranslateUi(self, Barely):
        _translate = QtCore.QCoreApplication.translate
        Barely.setWindowTitle(_translate("Barely", "Barely"))
        self.label.setText(_translate("Barely", "Now playing:"))
        self.now_playing_label.setText(_translate("Barely", "---"))
        self.prev_btn.setShortcut(_translate("Barely", "Ctrl+Left"))
        self.skip_back_btn.setShortcut(_translate("Barely", "Left"))
        self.play_pause_btn.setShortcut(_translate("Barely", "Space"))
        self.stop_btn.setShortcut(_translate("Barely", "S"))
        self.skip_forwards_btn.setShortcut(_translate("Barely", "Right"))
        self.next_btn.setShortcut(_translate("Barely", "Ctrl+Right"))
        self.current_position_label.setText(_translate("Barely", "--:--"))
        self.duration_label.setText(_translate("Barely", "--:--"))
        self.menuFile.setTitle(_translate("Barely", "File"))
        self.actionOpen.setText(_translate("Barely", "Open..."))
        self.actionClose.setText(_translate("Barely", "Close"))
        self.actionRemove_selected.setText(_translate("Barely", "Remove selected"))
        self.actionRemove_selected.setShortcut(_translate("Barely", "Backspace"))
        self.actionRemove_all.setText(_translate("Barely", "Remove all"))
        self.actionNext.setText(_translate("Barely", "Next"))
        self.actionNext.setShortcut(_translate("Barely", "Right"))
        self.actionPrevious.setText(_translate("Barely", "Previous"))
        self.actionPrevious.setShortcut(_translate("Barely", "Left"))
        self.actionPlay_pause.setText(_translate("Barely", "Play"))
        self.actionPlay_pause.setToolTip(_translate("Barely", "Play/Pause"))
        self.actionPlay_pause.setShortcut(_translate("Barely", "Space"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Barely = QtWidgets.QMainWindow()
    ui = Ui_Barely()
    ui.setupUi(Barely)
    Barely.show()
    sys.exit(app.exec_())
